version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: redisrelay-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    networks:
      - redisrelay-network
  redis-ui:
    image: redis/redisinsight
    container_name: redisrelay-redis-ui
    ports:
      - "5540:5540"
    restart: unless-stopped
    depends_on:
      - redis
    networks:
      - redisrelay-network
  redis-relay:
    build:
      context: .
      dockerfile: dockerfile
    container_name: redisrelay-relay
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      - redis
    networks:
      - redisrelay-network

networks:
 redisrelay-network:
    driver: bridge

volumes:
  redis-data:
